/**
 * Fragile magic. Do not touch.
 *
 * Just kidding, this file is autogenerated and changes will be overwritten on
 * the next build. To make changes, edit [library/build.js].
 */

import DonateButton from 'src/elements/DonateButton/DonateButton'
import VButton from 'src/elements/VButton/VButton'
import VCheckbox from 'src/elements/VCheckbox/VCheckbox'
import VRadio from 'src/elements/VRadio/VRadio'
import SlotRenderer from 'src/utilities/SlotRenderer/SlotRenderer'

// Export individual components
export {
  DonateButton,
  VButton,
  VCheckbox,
  VRadio,
  SlotRenderer
}

// Export as plugin
export const VueVocabulary = {
  install: function (Vue) {
    Vue.component('DonateButton', DonateButton)
    Vue.component('VButton', VButton)
    Vue.component('VCheckbox', VCheckbox)
    Vue.component('VRadio', VRadio)
    Vue.component('SlotRenderer', SlotRenderer)
  }
}
